name: sparkingCuriosity
channels:
  - conda-forge
dependencies:
  - python == 3.8.10
  - pip == 21.0
  - pip:
    - gensim == 3.5.0
    - nbgitpuller
    - sphinx-gallery
    - numpy == 1.20.3
    - matplotlib == 2.2.3
    - nltk == 3.3
    - networkx == 1.11