name: sparkingCuriosity
channels:
  - conda-forge
dependencies:
  - python=3.7
  - pip=3
  - pip:
    - nbgitpuller
    - sphinx-gallery
    - numpy
    - subprocess
    - os
    - pandas
    - re
    - sos
    - sos-notebook
    - json
    - pickle
    - urllib
    - matplotlib
    - nltk
    - networkx
    - gensim