name: sparkingCuriosity
channels:
  - conda-forge
dependencies:
  - python=3.7
  - pip=3
  - pip:
    - nbgitpuller
    - sphinx-gallery
    - numpy
    - sos
    - sos-notebook
    - matplotlib=2.2.3
    - nltk=3.3
    - networkx=1.11
    - gensim=3.5.0